name: CI Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Linux (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: [Debug, Release]
        include:
          - generator: Ninja
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install build-essential g++ cmake ninja-build libsdl2-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G ${{ matrix.generator }} -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ..
        cmake --build .
